---
- name: Uninstall Grafana
  shell: |
    helm uninstall grafana --namespace {{ _grafana.namespace }}
  register: uninstall_grafana
  ignore_errors: true
  args:
    chdir: "{{ base_path }}/"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg={{ uninstall_grafana }}
  when: print_debug == true


- name: Validate if Grafana Containers are Deleted Completedly
  shell: |
    kubectl get pods -n {{ _grafana.namespace }} | sed 1d | grep grafana- | awk '{print $3}' | grep -E 'Running|Terminating' | wc -l
  register: delete_grafana_container
  ignore_errors: true
  until: delete_grafana_container.stdout|int == 0
  retries: 100
  delay: 10
  args:
    chdir: "{{ base_path }}/"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg={{ delete_grafana_container }}
  when: print_debug == true


- import_tasks: delete-local-pv.yml
  when: _grafana.directpv == false


- name: Delete Namespace for Persistent Volumes
  shell: |
    kubectl delete namespace {{ _grafana.namespace }}
  register: delete_namespace
  ignore_errors: true
  args:
    chdir: "{{ base_path }}/"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg={{ delete_namespace }}
  when: print_debug == true

