deepseek:
	@if [ ! -z ${r} ] && [ "${s}" != "all" ]; then\
		if [ -z ${c} ];  then\
			ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-deepseek.yml -e '{"${s}": True}' --tags='${r}';\
		elif [ ! -z ${c} ];  then\
			if [ "${c}" = "all" ]; then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-deepseek.yml -e '{"${s}": True}' -e '{deepseek_all: True}' --tags='${r}';\
			elif [ "${c}" != "all" ]; then\
				ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-deepseek.yml -e '{"${s}": True}' -e '{"${c}": True}' --tags='${r}';\
			else\
				echo "No actions to ${r} deepseek";\
			fi;\
		else\
			echo "No actions to ${r} deepseek";\
		fi;\
	elif [ ! -z ${r} ] && [ "${s}" = "all" ]; then\
		if [ -z ${c} ];  then\
			ansible-playbook --ssh-common-args='-o UserKnownHostsFile=./known_hosts' -u ${USERNAME} setup-deepseek.yml -e '{deepseek_all: True}' --tags='${r}';\
		else\
			echo "No actions to ${r} deepseek";\
		fi;\
	else\
		echo "No actions to ${r} deepseek";\
	fi

