---
- name: Copy Local PVC Config Yaml
  template:
    src: "{{ item }}.j2"
    dest: "{{ base_path }}/{{ item }}"
  register: copy_local_pvc_config_yaml
  ignore_errors: true
  with_items:
    - "local-storage-class.yaml"
    - "local-storage-pv.yaml"
    - "local-storage-pvc.yaml"
- debug: msg={{ copy_local_pvc_config_yaml }}


- name: Delete Local PV
  shell: |
    kubectl delete -f {{ item }}
  register: delete_local_pvc
  ignore_errors: true
  with_items:
    - "local-storage-pv.yaml"
    - "local-storage-class.yaml"
    # - "local-storage-pvc.yaml"
  args:
    chdir: "{{ base_path }}/"
- debug: msg={{ delete_local_pvc }}
  when: print_debug == true


- name: Delete Local PV Config Yaml and Directory
  file:
    path: "{{ base_path }}/{{ item }}"
    state: absent
  register: delete_local_pv_config
  ignore_errors: true
  with_items:
    - "local-storage-pv.yaml"
    - "local-storage-class.yaml"
    - "local-storage-pvc.yaml"
- debug: msg={{ delete_local_pv_config }}
  when: print_debug == true


#- name: Delete Namespace for Local PV
#  shell: |
#    kubectl delete namespace {{ _ollama.namespace }}
#  register: delete_ollama_ns
#  ignore_errors: true
#- debug: msg={{ delete_ollama_ns }}
#  when: print_debug == true


#- name: Remove Directory for Persistent Volumes for Ollama
#  file:
#    path: "{{ _ollama.storage_path }}-{{ item }}"
#    state: absent
#  register: remove_pv_dir
#  with_sequence: start=0 end={{ ollama_total_pvs|int }}
#- debug: msg={{ remove_pv_dir }}
#  when: print_debug == true


