---
- name: Check OS ( DeepSeek )
  fail: msg="Not a Red Hat or SUSE based System!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky' or ansible_os_family != 'openSUSE Leap'


- name: Set facts for DeepSeek
  import_tasks: set-deepseek-facts.yml
  tags: install, uninstall, create, delete, setup, remove, apply, deploy, undeploy


- name: Enable Helm Repository
  import_tasks: enable-helm-repo.yml
  tags: enable, install
  when: (( repo is defined and repo == true ) or ( deepseek_all is defined and deepseek_all == true )) and inventory_hostname in groups['master']


- name: Apply Kernel Parameters for DeepSeek
  import_tasks: apply-deepseek-kernel-parameters.yml
  tags: apply, install
  when: ( param is defined and param  == true ) or ( deepseek_all is defined and deepseek_all == true )


- name: Install GO
  import_tasks: install-go.yml
  tags: setup, install
  when: (( go is defined and go == true ) or ( deepseek_all is defined and deepseek_all == true )) and inventory_hostname in groups['master']


- name: Create Local PV
  import_tasks: create-local-pv.yml
  tags: create, install
  when: (( pv is defined and pv == true ) or ( deepseek_all is defined and deepseek_all == true )) and inventory_hostname in groups['master']


- name: Install the Ollama Operator
  import_tasks: install-ollama-operator.yml
  tags: setup, install
  when: (( ollama is defined and ollama == true ) or ( deepseek_all is defined and deepseek_all == true )) and inventory_hostname in groups['master']


- name: Install the Kollama CLI
  import_tasks: install-kollama-cli.yml
  tags: setup, install
  when: (( kollama is defined and kollama == true ) or ( deepseek_all is defined and deepseek_all == true )) and inventory_hostname in groups['master']


- name: Install Ollama Cli
  import_tasks: install-ollama-cli.yml
  tags: setup, install
  when: (( ollacli is defined and ollacli == true ) or ( deepseek_all is defined and deepseek_all == true )) and inventory_hostname in groups['master']


- name: Deploy DeepSeek R1 Model
  import_tasks: deploy-model.yml
  tags: deploy, install
  when: (( model is defined and model == true ) or ( deepseek_all is defined and deepseek_all == true )) and inventory_hostname in groups['master']


- name: Deploy Open Web UI
  import_tasks: install-open-webui.yml
  tags: deploy, install
  when: (( ui is defined and ui == true ) or ( deepseek_all is defined and deepseek_all == true )) and inventory_hostname in groups['master']


- name: Install Load Balancer
  import_tasks: install-lb.yml
  tags: apply, install
  when: ( lb is defined and lb == true ) and inventory_hostname in groups['master']


- name: Install NGINX Ingress
  import_tasks: install-ingress.yml
  tags: apply, install
  when: (( apply, ingress is defined and ingress == true ) or ( deepseek_all is defined and deepseek_all == true )) and inventory_hostname in groups['master']


- name: Unstall NGINX Ingress
  import_tasks: uninstall-ingress.yml
  tags: delete, uninstall
  when: (( ingress is defined and ingress == true ) or ( deepseek_all is defined and deepseek_all == true )) and inventory_hostname in groups['master']


- name: Uninstall Load Balancer
  import_tasks: uninstall-lb.yml
  tags: delete, uninstall
  when: ( lb is defined and lb == true ) and inventory_hostname in groups['master']


- name: Destory Open Web UI
  import_tasks: uninstall-open-webui.yml
  tags: destroy, uninstall
  when: (( ui is defined and ui == true ) or ( deepseek_all is defined and deepseek_all == true )) and inventory_hostname in groups['master']


- name: Undeploy DeepSeek R1 Model
  import_tasks: undeploy-model.yml
  tags: undeploy, uninstall
  when: (( model is defined and model == true ) or ( deepseek_all is defined and deepseek_all == true )) and inventory_hostname in groups['master']


- name: Uninstall the Ollama Operator
  import_tasks: uninstall-ollama-operator.yml
  tags: remove, uninstall
  when: (( ollama is defined and ollama == true ) or ( deepseek_all is defined and deepseek_all == true )) and inventory_hostname in groups['master']


- name: Delete Local PV
  import_tasks: delete-local-pv.yml
  tags: delete, uninstall
  when: (( pv is defined and pv == true ) or ( deepseek_all is defined and deepseek_all == true )) and inventory_hostname in groups['master']


- name: Remove Kernel Parameters for DeepSeek
  import_tasks: remove-deepseek-kernel-parameters.yml
  tags: remove, uninstall
  when: ( param is defined and param == true ) or ( deepseek_all is defined and deepseek_all == true )


- name: Disable Helm Repository
  import_tasks: disable-helm-repo.yml
  tags: disable, uninstall
  when: (( repo is defined and repo == true ) or ( deepseek_all is defined and deepseek_all == true )) and inventory_hostname in groups['master']

