---
- name: Deploy DeepSeek R1 Model
  shell: |
    kollama undeploy {{ item  }} -n {{ _deepseek.namespace }}
  register: deploy_dsr1_model
  args:
    executable: /bin/bash
    chdir: "{{ base_path }}"
  environment:
    PATH: "/root/go/bin:{{ ansible_env.PATH }}"
  with_items:
    - deepseek-r1
    # - phi
    # - phi4
- debug: msg={{ deploy_dsr1_model }}
  when: print_debug == true

