---
- name: Uninstall the Ollama Operator
  shell: |
    kubectl -n {{ _ollama.namespace }} delete -f https://raw.githubusercontent.com/nekomeowww/ollama-operator/v{{ _ollama_version }}/dist/install.yaml
  register: uninstall_ollama_operator
- debug: msg={{ uninstall_ollama_operator }}
  when: print_debug == true

