---
- name: Delete DeepSeek Load Balancer
  shell: |
    kubectl patch svc {{ item.name }} -n {{ _deepseek.namespace }} -p '{"spec": {"type": "ClusterIP"}}'
  register: delete_deepseek_lb
  ignore_errors: yes
  args:
    chdir: "{{ base_path }}"
  with_items: "{{ _deepseek.svc }}"
- debug: msg={{ delete_deepseek_lb }}
  when: print_debug == true


- name: Print DeepSeek Services
  shell: |
    kubectl get svc -n {{ _deepseek.namespace }}
  register: print_deepseek_svc
  ignore_errors: yes
  args:
    chdir: "{{ base_path }}"
- debug: msg={{ print_deepseek_svc }}
  when: print_debug == true

