---
- name: Uninstall Web UI
  shell: |
    /usr/local/bin/helm uninstall open-webui -n {{ _deepseek.namespace }}
  register: uninstall_open_webui
  ignore_errors: true
  args:
    chdir: "{{ base_path }}"
- debug: msg={{ uninstall_open_webui }}
  when: print_debug == true


- name: Validate if Open Web UI Containers are Deleted
  shell: |
    kubectl get pods -n {{ _deepseek.namespace }} | grep open-webui | awk '{print $3}' | grep -E 'Terminating|Running' | wc -l
  register: delete_open_webui_container
  ignore_errors: true
  until: delete_open_webui_container.stdout|int == 0
  retries: 100
  delay: 10
- debug: msg={{ delete_open_webui_container }}
  when: print_debug == true


- name: Copy Open Web UI and PVC Config Yaml
  template:
    src: "{{ item }}.j2"
    dest: "{{ base_path }}/{{ item }}"
  register: copy_open_webui_config_yaml
  with_items:
    - "local-storage-open-webui-pvc.yaml"
- debug: msg={{ copy_open_webui_config_yaml }}


- name: Delete Open Web UI PVC
  shell: |
    kubectl -n {{ _deepseek.namespace }} delete -f local-storage-open-webui-pvc.yaml
  register: delete_open_webui_pvc
  ignore_errors: true
  args:
    chdir: "{{ base_path }}"
- debug: msg={{ delete_open_webui_pvc }}
  when: print_debug == true


- name: Delete Open Web UI and PVC Config Yaml
  file:
    path: "{{ base_path }}/{{ item }}"
    state: absent
  register: delete_open_webui_config
  ignore_errors: true
  with_items:
    - "open-webui-values.yaml"
    - "local-storage-open-webui-pvc.yaml"
- debug: msg={{ delete_open_webui_config }}
  when: print_debug == true

