---
base_path: /root


_kustomize:
  install: false
  download_url: "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
  major_version: 5
  minor_version: 4
  patch_version: 2


_go:
  download: true
  major_version: 1
  minor_version: 23
  patch_version: 10


_ollama:
  major_version: 0
  minor_version: 10
  patch_version: 7
  namespace: ollama-operator-system


_deepseek:
  download: true
  install: true
  major_version: 0
  minor_version: 10
  patch_version: 7
  admin_user: "admin"
  admin_password: "changeme"
  admin_email: "rokmc756@gmail.com"
  enable_discovery_daemon: false
  clone_git: true
  nvme: true
  namespace: deepseek
  storage_path: "/mnt/deepseek-storage"
  storage_class: "deepseek-storage"
  hostname: "deepseek.jtest.pivotal.io"
  service:
    metadata:
      name: deepseek-loadbalancer
      namespace: deepseek
  ingress:
    metadata:
      name: deepseek-ingress
      namespace: deepseek
    hostname: "deepseek.jtest.pivotal.io"
  kernel_parameters:
    - "net.ipv4.neigh.default.gc_thresh1 = 0"   # For ARP Cache
    - "fs.inotify.max_user_instances=2280"
    - "fs.inotify.max_user_watches=755360"
  svc:
    - { name: "ollama-models-store", lb_ip_addr: "192.168.1.221" }
    - { name: "open-webui", lb_ip_addr: "192.168.1.222" }
    - { name: "open-webui-ollama", lb_ip_addr: "192.168.1.223" }
    - { name: "open-webui-pipelines", lb_ip_addr: "192.168.1.224" }
    - { name: "open-webui-postgres", lb_ip_addr: "192.168.1.225" }

deepseek_total_pvs: 5
# deepseek_total_pvs: "{{ ( _deepseek.sharded_shard|int * _deepseek.shardsvr|int ) + _deepseek.configsvr|int }}"


# NAME                          TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)           AGE
# ollama-model-deepseek-r1-lb   LoadBalancer   10.101.81.199    192.168.1.210   11434:30913/TCP   11m


_helm:
  enable_repo: true
  major_version: 3
  minor_version:
  patch_version:
  build_version:


_nginx:
  ingress:
    install: true
    name: nginx-ingress
    class_name: deepseek-express-ingress-class
    namespace: "nginx-ingress"
    major_version:
    minor_version:
    patch_version:
    replica: 1
    hostname: deepseek-express
    domain: jtest.pivotal.io
    service: deepseek-express
    ip_addr: "192.168.1.219"
    port: 8081
  k8s_ingress:
    major_version: 3
    minor_version: 0
    patch_version: 2


_ssl:
  dir: "{{ base_path }}/deepseek-certs"
  days: 3660
  country: "KR"
  state: "Seoul"
  location: "Guro"
  organization: "Pivotal"
  common_name: "jest.pivotal.io"
  email: "rokmc756@gmail.com"

