---
base_path: /root


_kustomize:
  install: false
  download_url: "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
  major_version: 5
  minor_version: 4
  patch_version: 2


_go:
  download: true
  major_version: 1
  minor_version: 23
  patch_version: 10


_ollama:
  major_version: 0
  minor_version: 10
  patch_version: 7
  namespace: ollama-operator-system


_deepseek:
  download: true
  install: true
  major_version: 0
  minor_version: 10
  patch_version: 7
  admin_user: "admin"
  admin_password: "changeme"
  admin_email: "rokmc756@gmail.com"
  enable_discovery_daemon: false
  clone_git: true
  nvme: true
  namespace: deepseek
  storage_path: "/opt/deepseek-storage"
  storage_class: "deepseek-storage"
  hostname: "deepseek.jtest.pivotal.io"
  service:
    metadata:
      name: deepseek-loadbalancer
      namespace: deepseek
  ingress:
    metadata:
      name: nginx-ingress
      namespace: deepseek
    hostname: "deepseek.jtest.pivotal.io"
  kernel_parameters:
    - "net.ipv4.neigh.default.gc_thresh1 = 0"   # For ARP Cache
    - "fs.inotify.max_user_instances=2280"
    - "fs.inotify.max_user_watches=755360"
  svc:
    - { name: "ollama-models-store", lb_ip_addr: "192.168.1.221" }
    - { name: "open-webui-ollama", lb_ip_addr: "192.168.1.223" }
    - { name: "open-webui-pipelines", lb_ip_addr: "192.168.1.224" }
    - { name: "open-webui-postgres", lb_ip_addr: "192.168.1.225" }
    - { name: "open-webui-redis", lb_ip_addr: "192.168.1.226" }
    - { name: "open-webui-redis-master", lb_ip_addr: "192.168.1.227" }
    - { name: "open-webui-redis-replicas", lb_ip_addr: "192.168.1.228" }
    # - { name: "open-webui", lb_ip_addr: "192.168.1.222" }
    # - { name: "ollama-model-deepseek-r1-lb", lb_ip_addr: "192.168.1.220"
  replica:
    open_web_ui: 3
    redis_cluster: 3
    postgres: 1


deepseek_total_pvs: "{{ _deepseek.replica.postgres|int + _deepseek.replica.open_web_ui|int + _deepseek.replica.redis_cluster|int + 4 }}"


_helm:
  enable_repo: true
  major_version: 3
  minor_version:
  patch_version:
  build_version:


_nginx:
  ingress:
    install: true
    name: nginx-ingress
    class_name: deepseek-ingress-class
    namespace: "nginx-ingress"
    major_version:
    minor_version:
    patch_version:
    replica: 1
    hostname: open-webui
    domain: jtest.pivotal.io
    service: open-webui
    ip_addr: "192.168.1.229"
    port: 80
  k8s_ingress:
    major_version: 3
    minor_version: 0
    patch_version: 2


_ssl:
  dir: "{{ base_path }}/deepseek-certs"
  days: 3660
  country: "KR"
  state: "Seoul"
  location: "Guro"
  organization: "Pivotal"
  common_name: "jest.pivotal.io"
  email: "rokmc756@gmail.com"


