---
- name: Install MinIO Client ( mcli ) Package
  import_tasks: install-mcli-pkgs.yml


- name: Add Local MinIO Client Configuration
  shell: |
    mcli alias set myminio https://minio-api.jtest.pivotal.io admin changeme --insecure
  register: add_local_minio_client_config
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg="{{ add_local_minio_client_config }}"
  register: add_local_minio_client_config

