---
- name: Check OS ( Prometheus )
  fail: msg="Not a Red Hat or SUSE based System!"
  when: ansible_os_family != 'RedHat' or  ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky' or ansible_os_family != 'openSUSE Leap'


- name: Set facts for Prometheus
  import_tasks: set-prometheus-facts.yml
  tags: install, uninstall, apply, remove, deploy, destroy, enable, disable, config


- name: Prepare Environment such as Creating Directory and Applying Kernel Parameters
  import_tasks: prepare-prometheus-env.yml
  tags: prepare, install
  when: ( env is defined and env == true ) or ( prometheus_all is defined and prometheus_all == true )


- name: Enable Helm Repository
  import_tasks: enable-helm-repo.yml
  tags: enable, install
  when: (( repo is defined and repo == true ) or ( prometheus_all is defined and prometheus_all == true )) and inventory_hostname in groups['master']


- name: Install Kustomize
  import_tasks: install-kustomize.yml
  tags: setup, install
  when: (( kustomize is defined and kustomize == true ) or ( prometheus_all is defined and prometheus_all == true )) and inventory_hostname in groups['master']


- name: Deploy Kube Prometheus
  import_tasks: install-kube-prometheus.yml
  tags: deploy, install
  when: (( prometheus is defined and prometheus == true ) or ( prometheus_all is defined and prometheus_all == true )) and inventory_hostname in groups['master']


- name: Install Load Balancer
  import_tasks: install-lb.yml
  tags: setup, install
  when: (( lb is defined and lb == true ) or ( prometheus_all is defined and prometheus_all == true )) and inventory_hostname in groups['master']


- name: Install NGINX Ingress
  import_tasks: install-ingress.yml
  tags: setup, install
  when: (( ingress is defined and ingress == true ) or ( prometheus_all is defined and prometheus_all == true )) and inventory_hostname in groups['master']


- name: Configure MinIO Metrics
  import_tasks: config-minio-metrics.yml
  tags: config, install
  when: ( minio is defined and minio == true ) and inventory_hostname in groups['master']


- name: Unstall NGINX Ingress
  import_tasks: uninstall-ingress.yml
  tags: remove, uninstall
  when: (( ingress is defined and ingress == true ) or ( prometheus_all is defined and prometheus_all == true )) and inventory_hostname in groups['master']


- name: Uninstall Load Balancer
  import_tasks: uninstall-lb.yml
  tags: remove, uninstall
  when: (( lb is defined and lb == true ) or ( prometheus_all is defined and prometheus_all == true )) and inventory_hostname in groups['master']


- name: Destroy Prometheus
  import_tasks: uninstall-kube-prometheus.yml
  tags: destroy, uninstall
  when: (( prometheus is defined and prometheus == true ) or ( prometheus_all is defined and prometheus_all == true )) and inventory_hostname in groups['master']


- name: Disable Helm Repository
  import_tasks: disable-helm-repo.yml
  tags: disable, uninstall
  when: (( prometheus is defined and prometheus == true ) or ( prometheus_all is defined and prometheus_all == true )) and inventory_hostname in groups['master']


- name: Cleanup Environment such as Deleting Directory and Removing Kernel Parameters
  import_tasks: cleanup-prometheus-env.yml
  tags: clean, uninstall
  when: ( env is defined and env == true ) or ( prometheus_all is defined and prometheus_all == true )

