---
- name: Create Directory for Persistent Volumes
  file:
    # path: "{{ _prometheus.persistence.storage_path }}-{{ item }}"
    path: "{{ _prometheus.storage_path }}-{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  register: create_pv_dir
  with_sequence: start=0 end={{ total_prometheus_containers|int }}
  when: _prometheus.directpv == false
- debug: msg={{ create_pv_dir }}
  when: print_debug == true and _prometheus.directpv == false


- name: Apply Kernel Parameters
  lineinfile:
    dest: /etc/sysctl.d/sysctl-k8s.conf
    line: "{{ item }}"
    state: present
  register: apply_kernel_parameters
  with_items:
    - "{{ _prometheus.kernel_parameters }}"
  notify:
    - Reload Sysctl
- debug: msg={{ apply_kernel_parameters }}
  when: print_debug == true

