---
- name: Copy Prometheus Loadbalancer Config Yaml
  template:
    src: prometheus-loadbalancer.yaml.j2
    dest: "{{ base_path }}/prometheus-loadbalancer.yaml"
  register: copy_prometheus_lb_config_yaml
  ignore_errors: true
- debug: msg={{ copy_prometheus_lb_config_yaml }}


- name: Delete Prometheus Load Balancer
  shell: |
    kubectl patch svc {{ item.svc }} -n {{ _prometheus.namespace }} -p '{"spec": {"type": "ClusterIP"}}'
  register: delete_prometheus_lb
  ignore_errors: true
  args:
    chdir: "{{ base_path }}"
  with_items:
    - { svc: "kube-prometheus-alertmanager",       lb_ip_addr: "{{ _prometheus.alertmanager.ip_addr }}" }
    - { svc: "kube-prometheus-blackbox-exporter",  lb_ip_addr: "{{ _prometheus.blackbox_exporter.ip_addr }}" }
    - { svc: "kube-prometheus-kube-state-metrics", lb_ip_addr: "{{ _prometheus.kube_state_metrics.ip_addr }}" }
    - { svc: "kube-prometheus-node-exporter",      lb_ip_addr: "{{ _prometheus.node_exporter.ip_addr }}" }
    - { svc: "kube-prometheus-operator",           lb_ip_addr: "{{ _prometheus.operator.ip_addr }}" }
    - { svc: "kube-prometheus-prometheus",         lb_ip_addr: "{{ _prometheus.prometheus.ip_addr }}" }
- debug: msg={{ delete_prometheus_lb }}
  ignore_errors: true
  when: print_debug == true

