---
- name: Uninstall Prometheus
  shell: |
    /usr/local/bin/helm uninstall prometheus -n {{ _prometheus.namespace }}
  register: uninstall_prometheus
  ignore_errors: true
- debug: msg={{ uninstall_prometheus }}
  ignore_errors: true
  when: print_debug == true


- name: Validate if Prometheus Containers are Deleted
  shell: |
    kubectl get pods -n {{ _prometheus.namespace }} | grep {{ item.svc }} | awk '{print $3}' | grep -E "Running|Terminating" | wc -l
  register: check_prometheus_containers
  ignore_errors: true
  until: check_prometheus_containers.stdout|int == 0
  retries: 100
  delay: 10
  with_items:
    - { svc: "prometheus-server-", replica: "{{ _prometheus.server.replica }}" }
    - { svc: "prometheus-alertmanager-", replica: "{{ _prometheus.alertmanager.replica }}" }
- debug: msg={{ check_prometheus_containers }}
  when: print_debug == true


- import_tasks: delete-local-pv.yml
  when: _prometheus.directpv == false


- name: Delete Namespace for Persistent Volumes
  shell: |
    kubectl delete namespace {{ _prometheus.namespace }}
  register: delete_namespace
  ignore_errors: true
- debug: msg={{ delete_namespace }}
  ignore_errors: true
  when: print_debug == true


- name: Delete Prometheus Helm Config
  file:
    path: "{{ base_path }}/{{ item }}"
    state: absent
  register: delete_prometheus_helm_config
  with_items:
    - "prometheus-values.yaml"
- debug: msg={{ delete_prometheus_helm_config }}

