---
- name: Create Namespace for Persistent Volumes
  shell: |
    kubectl create namespace {{ _prometheus.namespace }}
  register: create_namespace
- debug: msg={{ create_namespace }}
  when: print_debug == true


- name: Deploy Prometheus
  shell: |
    /usr/local/bin/helm install prometheus prometheus-community/kube-prometheus-stack -n {{ _prometheus.namespace }}
  register: deploy_prometheus
- debug: msg={{ deploy_prometheus }}
  when: print_debug == true
# --version {{ prometheus_version }} --set image.tag={{ _prometheus.image_tag }} -f {{ base_path }}/prometheus-values.yaml


- name: Validate if Prometheus Controller Containers are Running
  shell: |
    kubectl get pods -n {{ _prometheus.namespace }} | grep {{ item.svc }} | awk '{print $3}' | grep Running | wc -l
  register: check_prometheus_containers
  until: check_prometheus_containers.stdout|int == 4
  #  item.replica|int
  retries: 100
  delay: 10
  with_items:
    - { svc: "prometheus-node-exporter", replica: "{{ _prometheus.replica }}" }
- debug: msg={{ check_prometheus_containers }}
  when: print_debug == true

