---
- name: Create Namespace for Persistent Volumes
  shell: |
    kubectl create namespace {{ _minio.namespace }}
  register: create_namespace
- debug: msg={{ create_namespace }}
  when: print_debug == true


- import_tasks: create-local-pv.yml
  when: _minio.directpv == false


- name: Copy MinIO Helm Config
  template:
    src: "{{ item }}.j2"
    dest: "{{ base_path }}/{{ item }}"
  register: copy_minio_helm_config
  with_items:
    - "minio-values.yaml"
- debug: msg={{ copy_minio_helm_config }}


- name: Deploy MinIO
  shell: |
    /usr/local/bin/helm install minio minio/minio -n {{ _minio.namespace }} -f {{ base_path }}/minio-values.yaml
  register: deploy_minio
- debug: msg={{ deploy_minio }}
  when: print_debug == true


- name: Validate if MinIO Controller Containers are Running
  shell: |
    kubectl get pods -n {{ _minio.namespace }} | grep {{ item.svc }} | awk '{print $3}' | grep Running | wc -l
  register: check_minio_containers
  until: check_minio_containers.stdout|int == item.replica|int
  retries: 100
  delay: 10
  with_items:
    - { svc: "minio-", replica: "{{ _minio.replica }}" }
- debug: msg={{ check_minio_containers }}
  when: print_debug == true

