---
base_path: "/root"

_krew:
  download_url: "https://github.com/kubernetes-sigs/krew/releases/latest/download"
  major_version:
  minor_version:
  patch_version:


_directpv:
  download_url: "https://github.com/minio/directpv/releases/download"
  major_version: 4
  minor_version: 1
  patch_version: 5


_nginx:
  ingress:
    install: true
    name: nginx-ingress
    class_name: korifi-ingress-class
    namespace: "nginx-ingress"
    major_version:
    minor_version:
    patch_version:
    replica: 1
    hostname: api
    domain: jtest.pivotal.io
    service: contour-korifi
    ip_addr: "192.168.1.224"
    port: 8081
  k8s_ingress:
    major_version: 3
    minor_version: 0
    patch_version: 2

