base_path: /root

_krew:
  base_path: "/root"
  download_url: "https://github.com/kubernetes-sigs/krew/releases/latest/download"
  major_version:
  minor_version:
  patch_version:

_directpv:
  base_path: "/root"
  download_url: "https://github.com/minio/directpv/releases/download"
  major_version: 4
  minor_version: 1
  patch_version: 5

_minio:
  install: true
  directpv: true
  major_version:
  minor_version:
  patch_version:
  build_version:
  admin_user: "admin"
  admin_password: "changeme"
  admin_email: "rokmc756@gmail.com"
  enable_discovery_daemon: false
  clone_git: true
  nvme: true
  namespace: minio
  storage_path: "/opt/minio-storage"
  # storage_class: "minio-storage"
  storage_class: "directpv-min-io"
  k8s:
    major_version: 1
    minor_version: 28
    patch_version: 0
    build_version:
  hostname: "minio0.jtest.pivotal.io"
  service:
    metadata:
      name: minio-loadbalancer
      namespace: minio
  ingress:
    metadata:
      name: minio-ingress
      namespace: minio
    hostname: "minio0.jtest.pivotal.io"
  kernel_parameters:
    - "net.ipv4.neigh.default.gc_thresh1 = 0"   # For ARP Cache
    - "fs.inotify.max_user_instances=2280"
    - "fs.inotify.max_user_watches=755360"
  lb:
    install: true
    ip_addr: 192.168.1.219
  replica: 16


total_minio_containers: "{{ _minio.replica|int }}"


_mc:
  download: false
  server_url: https://dl.minio.io/server/minio/release/linux-amd64/minio
  user_id: ""
  user: root
  service: minio
  user_home: /root
  config: "/root/.minio/config.json"
  client_config: /root/.mc/config.json
  bin: /usr/local/bin/minio
  port: 9000
  static_port: 9001
  client_install: yes
  client_url: https://dl.minio.io/client/mc/release/linux-amd64/mc
  client_checksum:
  client_bin: /usr/local/bin/mc
  client_admin_host:
  check_calendar: weekly
  config_opts:
    hosts:
      minio:
        url: http://minio-s3.jtest.pivotal.io:9000
        accessKey: "admin"
        secretKey: "changeme"
        api: S3v4
  release_date: 20240307
  access_key: jomoon
  secret_key: changeme
  minio_svc_alias: myminio


_nginx:
  ingress:
    install: true
    name: nginx-ingress
    class_name: minio-ingress-class
    namespace: "nginx-ingress"
    major_version:
    minor_version:
    patch_version:
    replica: 1
    hostname: minio0
    domain: jtest.pivotal.io
    service: minio-console
    ip_addr: "192.168.1.229"
    port: 9001
  k8s_ingress:
    major_version: 3
    minor_version: 0
    patch_version: 2


_helm:
  enable_repo: true
  major_version: 3
  minor_version:
  patch_version:
  build_version:


_ssl:
  dir: "{{ base_path }}/minio-certs"
  days: 3660
  country: "KR"
  state: "Seoul"
  location: "Guro"
  organization: "Pivotal"
  common_name: "jest.pivotal.io"
  email: "rokmc756@gmail.com"

